require "runic"

# Public: Bytecode Generator
class Runic::Generator
	# Public: Initialize a Generator
	def initialize
		@instructions = []
	end

	# Public: Returns the code generated by this generator
	def code
		Code.new @instructions.flatten(1)
	end
end